package com.wentt.openstack.model;

import java.io.Serializable;

public class TNetworkServerMap implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_network_server_map.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_network_server_map.network_id
     *
     * @mbggenerated
     */
    private String networkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_network_server_map.server_id
     *
     * @mbggenerated
     */
    private String serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_network_server_map
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_network_server_map.id
     *
     * @return the value of t_network_server_map.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_network_server_map.id
     *
     * @param id the value for t_network_server_map.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_network_server_map.network_id
     *
     * @return the value of t_network_server_map.network_id
     *
     * @mbggenerated
     */
    public String getNetworkId() {
        return networkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_network_server_map.network_id
     *
     * @param networkId the value for t_network_server_map.network_id
     *
     * @mbggenerated
     */
    public void setNetworkId(String networkId) {
        this.networkId = networkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_network_server_map.server_id
     *
     * @return the value of t_network_server_map.server_id
     *
     * @mbggenerated
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_network_server_map.server_id
     *
     * @param serverId the value for t_network_server_map.server_id
     *
     * @mbggenerated
     */
    public void setServerId(String serverId) {
        this.serverId = serverId;
    }
}